// src/types/kensho.d.ts
// Types for the Kensho system

/**
 * Extended Window interface for Kensho-specific properties
 */
export interface KenshoWindow extends Window {
  __kensho_workers?: Record<string, Worker>;
  __kensho_debug?: boolean;
}

/**
 * Event data structure for stream events
 */
export interface StreamEventData {
  type: string;
  data?: any;
  payload?: any;
  error?: Error;
}

/**
 * Message structure for inter-worker communication
 */
export interface WorkerMessage {
  type: string;
  payload?: any;
  messageId?: string;
  correlationId?: string;
  streamId?: string;
  error?: SerializedError;
}

/**
 * Serialized error structure for cross-worker communication
 */
export interface SerializedError {
  message: string;
  stack?: string;
  name: string;
  code?: string;
}

/**
 * Performance metrics structure
 */
export interface PerformanceMetrics {
  cpuUsage?: number;
  memoryUsage?: number;
  networkLatency?: number;
  batteryLevel?: number;
}

/**
 * Configuration options for Kensho components
 */
export interface KenshoConfig {
  mode: 'full' | 'lite' | 'simulation';
  llm: {
    enabled: boolean;
    autoload: boolean;
    model?: string;
  };
  debug: boolean;
  telemetry: boolean;
}

/**
 * Plan generated by the OIE for display in the UI
 */
export interface OIEPlan {
  type: string;
  thought: string;
  steps: Array<{
    id?: string;
    agent: string;
    action: string;
    args?: Record<string, any>;
    prompt?: string;
    label?: string;
  }>;
}

/**
 * Fact checking claims structure
 */
export interface FactCheckingClaim {
  claim: string;
  verification: string;
  sources: string[];
  confidence: number;
}

/**
 * Semantic search results structure
 */
export interface SemanticSearchResults {
  query: string;
  results: Array<{
    id: string;
    title: string;
    content: string;
    relevance: number;
  }>;
}

// Extend the global Window interface
declare global {
  interface Window extends KenshoWindow {}
}

export {};